version: '3.1'
services:
  elasticsearch:
    image: elasticsearch
    container_name: es_master
    environment:
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - ./conf/master/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/master:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

  elasticsearch_slaver:
    image: elasticsearch
    container_name: es_slaver
    environment:
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - ./conf/slaver/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/slaver:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: kibana
    container_name: es_cluster_kibana
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      SERVER_NAME: kibana
#      ELASTICSEARCH_URL: http://es_master:9200
      ELASTICSEARCH_HOSTS: http://es_master:9200
    ports:
      - 5601:5601
    networks:
      - esnet

  elasticsearch-head:
    image: mobz/elasticsearch-head:5
    container_name: es_cluster_head
    ports:
      - 9100:9100

networks:
  esnet: