version: '3.1'
services:
  kibana:
    image: kibana
    container_name: kibana
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      SERVER_NAME: kibana
#      ELASTICSEARCH_URL: http://192.168.46.99:9200
#      ELASTICSEARCH_HOSTS: http://elasticsearch.example.org
    ports:
      - 5601:5601