version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: MyRabbitmq
    privileged: true
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev
    volumes:
      - /opt/docker/rabbitmq/config:/etc/rabbitmq
      - /opt/docker/rabbitmq/logs:/var/log/rabbitmq
      - /opt/docker/home:/var/lib/rabbitmq
    command: rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_federation_management rabbitmq_stomp