version: '3.1'
services:
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    volumes:
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
    ports:
      - 9200:9200
      - 9300:9300

  head:
    image: mobz/elasticsearch-head:5
    container_name: elasticsearch-head
    ports:
      - 9100:9100