version: '3.1'
services:
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
    ports:
      - 9200:9200
      - 9300:9300