version: '3.1'
services:
  haproxy:
    image: haproxy
    container_name: haproxy
#    restart: always
    volumes:
      - ./conf:/usr/local/etc/haproxy
    privileged: true
    expose:
      - 80
      - 9000
    ports:
      - 80:80
      - 9000:9000