version: '3.1'
services:
  mysql:
    image: mysql:5.7.25
    container_name: MySql
 #   restart: always
    ports:
      - 3306:3306
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
      - ./logs:/logs
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    privileged: true