version: '3.1'
services:
  redis:
    image: redis
    container_name: MyRedis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./conf:/etc/redis/conf
      - ./data:/data
    command: redis-server /etc/redis/conf/redis.conf --protected-mode no